Support `freezed` 1.0
flutter-stripe/flutter_stripe pull request #450
Opened 2021-11-18 03:23 UTC by AlexV525

2021-11-18 03:26 UTC, AlexV525 commented
I'm not sure whether `freezed` files need to be updated too. If not, I can make a rebase.

2021-11-22 17:27 UTC, remonh87 requested changes
Thanks for creating this PR! IF you can revert the version bump in the pub spec yaml. We are good to go

2021-11-22 17:27 UTC, remonh87 commented on packages/stripe_platform_interface/pubspec.yaml
> +version: 2.0.3
Can you revert this? Version bump is not needed we use Melos to bump and publish the versions

2021-11-23 07:43 UTC, remonh87 approved these changes

2021-11-23 08:36 UTC, merged

2021-11-29 02:56 UTC, AlexV525 commented
Publish?

2021-12-10 07:47 UTC, AlexV525 commented
@remonh87 Please publish this when you have time for it, we've been blocked from it for nearly a month.

2021-12-10 09:45 UTC, remonh87 commented
@AlexV525  we want to incorporate two other features in this release. There is no need to be blocked you can add an override in your app. I did this for my project as well. We will publish this fix before Christmas for sure (whether or not the 2 other features are implemented).

`dependency_overrides:   freezed_annotation: ^1.0.0`

2021-12-10 09:48 UTC, AlexV525 commented
We can make an override for sure, it's all about consistency.